services:
  db:
    container_name: CakeDB
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pulpa_rico777
      POSTGRES_DB: codenamecake
      PGDATA: /data/postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      # this is the critical part of this file, the port mapping
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: